name: Marp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm_config_yes=true npx @marp-team/marp-cli@latest slide.md -o build/index.html
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
